### ISSUE TITLE
Maybe this app can help with adb.

### ISSUE THREAD

**Issue by gotmilo** [brevent/Brevent#24]
https://play.google.com/store/apps/details?id=moe.shizuku.privileged.api

**Comment by liudongmiao** [comment]
Actually, this app use the idea and codes of Brevent, without mention.

> Thanks to an app who provides ideas and some code, Shizuku Server was born. It also makes non-root usages become possible (via adb).

The mentioned "an app", is Brevent.

If you have rooted, there is root method, however, if you have such question, it just because you don't read guide carefully, and don't know there is root in Brevent.

And, Brevent have better code styles.

I even add a issue, however, as the author is too young, and i delete it: https://github.com/RikkaW/Shizuku/issues/1

Furthermore, as I keep updated Brevent-Server close-source, the project don't get updated idea.
