### ISSUE TITLE
Timeout,The start process is Timeout

### ISSUE THREAD

**Issue by 1558204459** [brevent/Brevent#311]
I try to active the brevent by using adb shell from computer
But it report that the start is timeout
This is the output log:

```
C:\Users\lenovo>adb -s LGMG600S -d shell sh /data/data/me.piebridge.brevent/brevent.sh
found old brevent_server, pid: 19630, killing
checking for server...started, pid: 20130
checking for stable.......timeout

if you find any issues, please report bug to https://github.com/brevent/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

```

**Comment by liyufan** [comment]
Check whether Brevent is the foreground(top) app.
`timeout` means Brevent cannot receive response from brevent server due to restriction of accessing local network.

**Comment by 1558204459** [comment]
Yes
I open it at the foreground(you mean fg from top? I haven't check this)
But my system load is very high,Some app which i haven't find out consumed much system resource 
I think the high system load lead this issues,Is there any optimization in your script to avoid such situation,especially in such high system load situation

**Comment by liyufan** [comment]
Actually when it reminds you `timeout`, brevent server has started successfully. Try to swipe Brevent from your `recent screen` and launch Brevent again. If Brevent doesn't pop a window which says
> Brevent can't access local network
>
then simply ignore this because Brevent is working well.
About `high system load` you mentioned above, it is likely that system cannot process request by Brevent in time. However, Brevent itself cannot determine how the system load is when you start brevent server, so when Brevent doesn't receive response from server in a specified time, it will remind you `timeout`. I suggest just reboot your device and system load will probably go down and everything will be ok.
